### PR TITLE
Feature/rewrite

### PR DESCRIPTION
**Pull request by saubaer**
fixes issues:
#2 (sum function)
#6 (unit tests. Unit, not integration)
#7 (keys & values are real JavaScript arrays now)

and improves performance.
Mind the performance unit test is not significant since Android behaves a bit different, mainly the GC.

### CODE REVIEW

**Comment by hideki** [comment]
Hi @saubaer,
Thank you very much for your PR.
One request, test case uses `gson`, Couchbase Lite Android/Java historically has used [Jackson](http://jackson.codehaus.org/) for JSON parser. And Jackson is already dependent module of CBL Java Core module (https://github.com/couchbase/couchbase-lite-java-core/blob/master/build.gradle#L18-L20). Could you please replace json with jackson?
I will review your PR carefully during next week.
Thanks!
Hideki

**Comment by hideki** [comment]
Performance test result with using one of user's test tool
https://github.com/couchbase/couchbase-lite-java-core/issues/630#issuecomment-103300014

By applying this PR, indexing performance improves around 6 times for PhoneGap.

**Comment by saubaer** [comment]
Hi @hideki,
the gson is only used in unit test for equals(), I will have a look at it. Maybe I can get rid of the json conversion. I can only work on that on weekends, so it will take a bit.

**Comment by hideki** [comment]
Hi @saubaer,
Your PR is really effective for performance. We might change it by ourself before weekend. Thanks for your amazing contribution!

**Comment by saubaer** [comment]
Only 6 times the performance for PhoneGap is a bit of a bummer, my simple tests showed a bit more of improvement.

**Comment by hideki** [comment]
Test is executed with PhoneGap app. So, it is not only pure map/reduce engine test. 6 times improvements are great.

**Comment by hideki** [comment]
Note to self:

Codes looks good and clean.

TODOs after signing contributor agreement.
- Add existing Unit test cases to new Unit tests 
- Replace Gson with Jackson
- Apply standard coding style
- Merge

**Comment by tleyden** [comment]
@saubaer awesome work!  Were you able to get past the contributor license friction?  I realize this sucks, but it's a legal thing to protect us getting sued for copyright infringement.

**Comment by hideki** [comment]
Hi @saubaer

I'd like to nominate you for Couchbase Community Champions.

```
Following on from our opening of the Couchbase Developer Expert (CDE) program we're  now looking to have nominations submitted  for the Couchbase Community Champions we are meeting through our engagement.  

Perhaps it's someone you've engaged with them on IRC, Forums, Stack Exchange, or submitted a patch, built something cool using Couchbase. If they are championing bringing in Couchbase into an organisation and steering converations towards Couchbase over other solutions please let us know.

We want to reach out and say thanks and give them a shout out in our newsletter and a small gift! 
```

Can I use your email which is showed in your commits?

Thanks,
Hideki

**Comment by saubaer** [comment]
Hi @ hideki

yes you can, thanks for asking and thanks for the nomination.

**Comment by hideki** [comment]
Hi @saubaer,

Thank you very much for your wonderful PR. We are really excited about performance improvement by your PR.

Cheers!

**Pull request merged**
